### ISSUE TITLE
Bedtool error

### ISSUE THREAD

**Issue by emmannaemeka** [Gabaldonlab/jloh#1]
Hi

I managed to get jloh to run but this error came up. Find below the error message

/Users/emmannaemeka/Documents/bioiformatics_program/jloh/jloh extract  --vcf b9_jlohcall_con.vcf  --ref   /Users/emmannaemeka/Documents/cglabarata/cbs138.fasta   --bam  /Users/emmannaemeka/Documents/cglabarata/cglbarata_analaysis/cglabara_analysis/ger_bam/b9.bam   
[Mon Mar 27 20:31:58 2023] Preparing workspace...
[Mon Mar 27 20:31:58 2023] Running in default mode...
[Mon Mar 27 20:31:58 2023] Extracting heterozygous and homozygous SNPs...
[Mon Mar 27 20:31:59 2023] Found 3410 heterozygous SNPs and 59669 homozygous SNPs
[Mon Mar 27 20:31:59 2023] Getting hetero- and homozygous SNP density...
[Mon Mar 27 20:31:59 2023] Homozygous SNPs/kbp: 4.73
[Mon Mar 27 20:31:59 2023] Heterozygous SNPs/kbp: 0.31
[Mon Mar 27 20:31:59 2023] Creating a file with chromosome lengths...
[Mon Mar 27 20:31:59 2023] Done
[Mon Mar 27 20:31:59 2023] Creating temporary bam files by chromosome ...
[Mon Mar 27 20:32:52 2023] Done
[Mon Mar 27 20:32:52 2023] Clustering heterozygous and homozygous SNPs into blocks...
Traceback (most recent call last):
  File "/Users/emmannaemeka/Documents/bioiformatics_program/jloh/src/extract", line 1436, in <module>
    main(args, tmp_bams)
  File "/Users/emmannaemeka/Documents/bioiformatics_program/jloh/src/extract", line 1423, in main
    tmp = run_in_default_mode(args, tmp_bams)
  File "/Users/emmannaemeka/Documents/bioiformatics_program/jloh/src/extract", line 1151, in run_in_default_mode
    Het_blocks, Homo_blocks_REF, Homo_blocks_ALT = snps_to_bed_blocks(args, Vcfs["hetero"][0], Vcfs["homo"][0], genome_file, args.min_snps_kbp)
  File "/Users/emmannaemeka/Documents/bioiformatics_program/jloh/src/extract", line 525, in snps_to_bed_blocks
    Het_bed_blocks = BedTool(Het_bed_blocks).merge(d=merge_len, c=4, o="sum")
  File "/Users/emmannaemeka/mambaforge/lib/python3.9/site-packages/pybedtools/bedtool.py", line 923, in decorated
    result = method(self, *args, **kwargs)
  File "/Users/emmannaemeka/mambaforge/lib/python3.9/site-packages/pybedtools/bedtool.py", line 402, in wrapped
    stream = call_bedtools(
  File "/Users/emmannaemeka/mambaforge/lib/python3.9/site-packages/pybedtools/helpers.py", line 460, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools merge -o sum -i /var/folders/qr/x2s0dbd137d0pg3c4sfcfhhm0000gn/T/pybedtools.huqezd4e.tmp -d 99 -c 4

Error message was:
Error: Unable to open file /var/folders/qr/x2s0dbd137d0pg3c4sfcfhhm0000gn/T/pybedtools.huqezd4e.tmp. Exiting.

**Comment by MatteoSchiavinato** [comment]
It seems as if it is unable to use the temporary directory that pybedtools creates. Two questions:

- Do you work from a mounted folder? 
- Do you have pybedtools installed in your python local lib, or is it a mounted module from an HPC cluster?

**Comment by emmannaemeka** [comment]
Thanks for your reply,
I am running on my laptop. Not from a mounted folder.
Do you have pybedtools installed in your python local lib, or is it a mounted module from an HPC cluster?

I tried to confirm by running

pip install pybedtools
Requirement already satisfied: pybedtools in /Users/emmannaemeka/mambaforge/lib/python3.9/site-packages (0.9.0)
Requirement already satisfied: six in /Users/emmannaemeka/mambaforge/lib/python3.9/site-packages (from pybedtools) (1.16.0)
Requirement already satisfied: pysam in /Users/emmannaemeka/mambaforge/lib/python3.9/site-packages (from pybedtools) (0.19.0)

Yes, I have it already installed

**Comment by MatteoSchiavinato** [comment]
Ok, can you please ensure that you have the correct version of all the dependencies listed in this page? 

https://github.com/Gabaldonlab/jloh/blob/master/docs/INSTALL.md

**Comment by MatteoSchiavinato** [comment]
I'm going to have to ask you for a minimal dataset that reproduces the error. I have no idea what is going on just by looking at the error.

Please upload a minimal dataset that reproduces the error somewhere and send me a link to test it! I will be on holiday until Monday so it will be next week.

**Comment by MatteoSchiavinato** [comment]
The new  [v0.20.0](https://github.com/Gabaldonlab/jloh/releases/tag/v0.20.0) release should solve this problem. It has with my own test dataset.
