### ISSUE TITLE
Error running Jloh from docker

### ISSUE THREAD

**Issue by Rahmmy** [Gabaldonlab/jloh#3]
Hello,
I was able to successfully pull the docker image using 
`docker pull cgenomics/jloh`

However when I run the test command `docker run --rm -t -i cgenomics/jloh --help` , I get this error below

`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--help": executable file not found in $PATH: unknown.`

Please advice,
Regards,
Abdul-Rahman

**Comment by MatteoSchiavinato** [comment]
Hi, 

Nothing is wrong in what you did, except that you are not actually calling the executable but rather just asking for its help. 

The correct command is: 

```
docker run -t -i --rm cgenomics/jloh jloh --help
```

Note that I removed `-t -i`, as you won't be needing an interactive session.

**Comment by Rahmmy** [comment]
Hello,
Thanks for the reply. It makes sense.
I was following the instructions on the installation (https://jloh.readthedocs.io/en/latest/usage/installation.html) website which only mentioned `docker run --rm -t -i cgenomics/jloh --help` without the executable.  
Thanks for the clarification.

It is working now.

**Comment by MatteoSchiavinato** [comment]
You are absolutely right, it is an oversight on our side. We will correct the docs!
