### ISSUE TITLE
Error running the jloh stats command 

### ISSUE THREAD

**Issue by Rahmmy** [Gabaldonlab/jloh#6]
Hello @MatteoSchiavinato ,

Thanks for resolving the previous issues.
Using the new version, I was able to successfully ran the `stats` command `/jloh stats --vcf out.ff.vcf` on the test data.

I then tried command on my own snp data for the _C. albicans_ WGS data called with gatk.

This gave the error below

`Traceback (most recent call last):
  File "/Users/abdurahman/JLOH_1/jloh/src/stats", line 313, in <module>
    main(args)
  File "/Users/abdurahman/JLOH_1/jloh/src/stats", line 256, in main
    Hetero_lines, Homo_lines = hetero_and_homo_snps(args.vcf)
  File "/Users/abdurahman/JLOH_1/jloh/src/stats", line 93, in hetero_and_homo_snps
    dict = { annotations[i]:values[i] for i in range(0, len(annotations)) }
  File "/Users/abdurahman/JLOH_1/jloh/src/stats", line 93, in <dictcomp>
    dict = { annotations[i]:values[i] for i in range(0, len(annotations)) }
IndexError: list index out of range`

I tried with different samples and each gave the same error.
Any suggestions on this?

Kind regards,
Abdul-Rahman

**Comment by MatteoSchiavinato** [comment]
Hi, 

This is very likely due to the fact that your VCF file does not have `AF` in the genotype or format annotation of each variant. This is the field used to determine if a SNP is truly heterozygous or not. 

You can clone this repo of mine:
https://github.com/MatteoSchiavinato/all2vcf

And use its module "frequency" to add it easily ;)

**Comment by Rahmmy** [comment]
Thanks for the feedback @MatteoSchiavinato. 
I successfully used the `all2vcf` to add the AF but the `stats` gave the same error

`[Tue Oct 24 11:48:46 2023] Reading SNPs
Traceback (most recent call last):
  File "/Users/abdurahman/JLOH_1/jloh/src/stats", line 313, in <module>
    main(args)
  File "/Users/abdurahman/JLOH_1/jloh/src/stats", line 256, in main
    Hetero_lines, Homo_lines = hetero_and_homo_snps(args.vcf)
  File "/Users/abdurahman/JLOH_1/jloh/src/stats", line 93, in hetero_and_homo_snps
    dict = { annotations[i]:values[i] for i in range(0, len(annotations)) }
  File "/Users/abdurahman/JLOH_1/jloh/src/stats", line 93, in <dictcomp>
    dict = { annotations[i]:values[i] for i in range(0, len(annotations)) }
IndexError: list index out of range`

**Comment by Rahmmy** [comment]
My all2vcf command is
`./all2vcf/all2vcf frequency -i TVY2_d0_V11.vcf -o TVY2_d0_AF_V11.vcf`

The jloh stats command is 
`./jloh stats --vcf TVY2_d0_AF_V11.vcf`

A SNP line from vcf file with AF inserted is
`Ca22chr1A_C_albicans_SC5314     33      .       C       T       3823.30 PASS    AC=18;AF=0.077;AN=234;BaseQRankSum=3.47;DP=16888;ExcessHet=0.0000;FS=18.495;InbreedingCoeff=0.3684;MLEAC=97;MLEAF=0.415;MQ=59.71;MQRankSum=0.00;QD=25.36;ReadPosRankSum=2.81;SOR=0.093  GT:AD:DP:GQ:PL:AF       ./.:0,0:0:0:0,0,0:0.077`

Thanks

**Comment by MatteoSchiavinato** [comment]
Right off the bat I don't see any issue with your file. Would you be willing to send it to me?

**Comment by Rahmmy** [comment]
Sure

**Comment by MatteoSchiavinato** [comment]
I had some time to assess your situation, but I see that your VCF file only has one SNP and this SNP has `AF=0.077`. Perhaps this is the reason, as the number of SNPs to compute density from is too low. 

I will edit the code to include a condition that warns the user about that in the next release. 

Should it contain one SNP only?

**Comment by Rahmmy** [comment]
Thanks for looking over the file.
I just double-checked. The [file](https://drive.google.com/file/d/1ZNi6iRL0QehERX4lKaC-hI4N88Lo6wfd/view?usp=drive_link) in the drive is 221.2 MB in size, with over 10k SNPs with varying AF.

**Comment by MatteoSchiavinato** [comment]
Ok, maybe google drive doesn't download the while thing well. I'll give it a try after the holiday (tomorrow).

**Comment by Rahmmy** [comment]
OKay thanks

**Comment by MatteoSchiavinato** [comment]
Hi, do you still have issues with this? I forgot to look into it but I also haven't heard back from you.
