### ISSUE TITLE
Error running jloh extract

### ISSUE THREAD

**Issue by nityendra21** [Gabaldonlab/jloh#7]
Hello, I'm getting numerous error when running `jloh` on the test data.
`version: 1.0.2`
Command: 
`./jloh extract --vcf test_data/out.ff.vcf --bam test_data/out.fs.bam --ref test_data/S_para.chrXII.fa --threads 40`

I have attached the full log:
[jloh_error.log](https://github.com/Gabaldonlab/jloh/files/13198676/jloh_error.log)

Thanks in advance!

**Comment by MatteoSchiavinato** [comment]
Hi, I checked your log and it looks like it's a multiprocessing problem, not a jloh problem. I see you're passing `--threads 40`, how many CPUs does the system you use it on have?

**Comment by nityendra21** [comment]
Hi @MatteoSchiavinato, the HPC node I'm running `jloh` on has 40 threads with 380GB of RAM. I have tried runnning `jloh` with lesser number of `--threads` ranging from 4 to 16. I'll try running `jloh` on a different machine.

**Comment by MatteoSchiavinato** [comment]
And the genome you're running it on, how large is it?

**Comment by nityendra21** [comment]
This is on the test set that you have provided in `test_data` that you have provided with `jloh`.

**Comment by MatteoSchiavinato** [comment]
Ok, then it likely is a problem of the system. We tested it on a similar system as yours, multiple users and multiple datasets. Perhaps consider giving a try to the docker image of JLOH at docker hub, maybe it solves it!

**Comment by nityendra21** [comment]
The issue is that our HPC cluster for some reason hasn't been updated to run Docker, I'll try running `jloh` locally, thanks for the advice!

**Comment by MatteoSchiavinato** [comment]
I'm closing it for now, feel free to reopen it if you have new information.
