### ISSUE TITLE
Adding labels in jloh plot

### ISSUE THREAD

**Issue by nityendra21** [Gabaldonlab/jloh#9]
Hello, 
I was wondering if there was a way to add labels when plotting LOH blocks using `jloh plot`? I can successfully plot the LOH blocks but the y-axis label that should contain the sample name is being labelled as NA. Also, is there a way to display the genome size on the x-axis when using the `--merge` flag? 

![P1_132 merged loh](https://github.com/Gabaldonlab/jloh/assets/85573898/e154431e-60e5-463d-bbf3-f09e217c5f1a)

**Comment by MatteoSchiavinato** [comment]
Hi, thanks for opening the issue. I'm afraid what you catched here is a bug, it should display the sample name. If you pass multiple samples and use `--names` together with it, it will name each row with each sample. Try passing a names file to `--names` with one row only that is the filename <tab> sample name (follow `--help` instructions). That should be a nice workaround, I'll fix it in the next release! 

Regarding the genome size, there is no automatic way. But you can easily add it yourself with an svg editor like inkscape!

**Comment by nityendra21** [comment]
Thanks for the suggestion!
